---
title: 'Exercises'
output: 
  html_document:
    toc: false
---

```{r setup-ex, include=FALSE}
library(knitr)
library(stringr)
knitr::opts_chunk$set(message=FALSE, warning=FALSE, eval=TRUE, echo=FALSE)
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(stringr))
```

\  

### Reproducible reports using R markdown

\  

- [R markdown exercise 1](Rmarkdown_ex1.html)

- [R markdown exercise 2](Rmarkdown_ex2.html)

\  

### Case study group work 

\ 

- [Case study group work exercise](case_study_group_work.html)

\  

If you want to work alongside my solutions you can find the relevant files below. Download the R markdown file and open it in your RStudio project.

- [Hediste case study R markdown file](case_study_hediste.Rmd)

- [Hediste case study final rendered html file](case_study_hediste.html)

- [Hediste case study final rendered pdf file](case_study_hediste.pdf)

\  

- [Hawaiian bird case study R markdown file](case_study_hawaiian_birds.Rmd)

- [Hawaiian bird case study final rendered html file](case_study_hawaiian_birds.html)

- [Hawaiian bird case study final rendered pdf file](case_study_hawaiian_birds.pdf)

\   

### Dealing with Variance heterogeneity 

\  

- [Dealing with variance heterogeneity exercise](GLS_variance_heterogeneity_exercise.html)

\  

If you want to work alongside my solutions you can find the relevant files below. Download the R markdown file and open it in your RStudio project.

- [Dealing with variance heterogeneity R markdown file](GLS_variance_heterogeneity_report.Rmd)

- [Dealing with variance heterogeneity final rendered html file](GLS_variance_heterogeneity_report.html)

- [Dealing with variance heterogeneity final rendered pdf file](GLS_variance_heterogeneity_report.pdf)

\  

### Dealing with temporal non-independence

\  

- [Dealing with temporal non-independence exercise](GLS_temporal_nonindependence_exercise.html)

\  

If you want to work alongside my solutions you can find the relevant files below. Download the R markdown file and open it in your RStudio project.

- [Dealing with temporal non-independence R markdown file](GLS_temporal_nonindependence_report.Rmd)

- [Dealing with temporal non-independence final rendered html file](GLS_temporal_nonindependence_report.html)

- [Dealing with temporal non-independence final rendered pdf file](GLS_temporal_nonindependence_report.pdf)

\  

### Dealing with spatial non-independence

\  

- [Dealing with spatial non-independence exercise](GLS_spatial_nonindependence.html)

\  

If you want to work alongside my solutions you can find the relevant files below. Download the R markdown file and open it in your RStudio project.

- [Dealing with spatial non-independence R markdown file](GLS_spatial_nonindependence_report.Rmd)

- [Dealing with spatial non-independence final rendered html file](GLS_spatial_nonindependence_report.html)

- [Dealing with spatial non-independence final rendered pdf file](GLS_spatial_nonindependence_report.pdf)

\  

### Mixed effects models 

\  

- [Mixed effects model exercise](Mixed_Models_Exercise.html)

\  

If you want to work alongside my solutions you can find the relevant files below. Download the R markdown file and open it in your RStudio project.

- [Mixed effects model R markdown file](Mixed_Models_report.Rmd)

- [Mixed effects model final rendered html file](Mixed_Models_report.html)

- [Mixed effects model final rendered pdf file](Mixed_Models_report.pdf)

\  
  